### ISSUE TITLE
Missing part of code in Readme for Azure AD configuration

### ISSUE THREAD

**Issue by ghost** [matik12/aurelia-oauth#17]
In Readme file, provided example for Azure AD configuration is missing import for OAuthTokenService
`import { OAuthService, OAuthTokenService } from 'aurelia-oauth';`

**Comment by matik12** [comment]
Hi @Junsui,

thanks for your note. 
I updated the ReadMe file by removing declared type for OAuthTokenService plugin configuration parameter. In case of Azure we don't need to configure token service, because the plugin is already configured to communicate with that particular SSO. Thus, we don't need to import OAuthTokenService type from plugin definition files. We don't use it during configuration and strong type is not needed. 

Thanks and take care,
Mat
