### ISSUE TITLE
Authorization code flow

### ISSUE THREAD

**Issue by brijan** [matik12/aurelia-oauth#2]
HI matik12
Currently, this plugin supports implicit grant flow. Is there any way that I can do similar with Authorization code flow

**Comment by PeterWone** [comment]
Unless I'm mistaken, authorization code flow is for server-server interactions. This is a SPA plugin for developing client software therefore no ACF.

**Comment by matik12** [comment]
Hi **brijan**,

I am sorry for a late response. As **PeterWone** mentioned this plugin only supports implicit grant flow which is recommended for Single Page Application according to OAuth2 Authorization Framework specification. Authorization code flow can be used when flow is implemented on the server side (not client side code) because it requires to store secret key to obtain access token. This can be only secured when key is stored on the sever side. 

If I can help with anything else, please just ask :)

Mat
