### ISSUE TITLE
jwt-token-service can't handle facebook tokens

### ISSUE THREAD

**Issue by PeterWone** [matik12/aurelia-oauth#5]
Facebook tokens are not base64 encoded JWT.

You decode them like this:

```
GET graph.facebook.com/debug_token?
     input_token={token-to-inspect}
     &access_token={app-token-or-admin-token}
```

The problem with that is it's asynchronous. I tried rewriting the jwtTokenService so that createToken returns immediately with a token containing a null value for getJwtClaims and getJwtClaims fills closes over the IOAuthTokenData object and fills in the missing values as soon as they are ready. But this is not enough, whatever is using the claims needs to wait for the values to be provided and I have yet to figure out where to make that change.

**Comment by matik12** [comment]
Hi again **PeterWone**

sorry for the late response, as I remember you have forked/copy this plugin repository to reflect the changes you need to make for your business case to support changing providers. 
If you need to get token claims from facebook api you could do as follows:
- Start with changing **JwtTokenService** and **getJwtClaims** method - basically you can remove existing code, private methods ect, but add http call to facebook api and return response with decoded token as a promise from this public method 
- Then change **createToken** method in **OAuthTokenService**, to perform getting claims with expiration date and create new object for token to be invoke on getJwtClaims promise resolove(then). This means that, createToken method should also return promise, but with type of IOAuthTokenData.
- Last thing is to adjust **OauthService** to the changes we made, first change **getTokenDataFromUrl** method to simply return promise from this.oAuthTokenService.createToken(hashData). Then change **setTokenOnRedirect** body to wait until this.getTokenDataFromUrl() promise is resolved (use than chain) and only then perform the rest of its code (if statement and its content, which should save token). 

If you follow my instructions, then code flow should be asynchronous and everything should be working as you expect. I guess the reason it was throwing an error, because OAuthToken service uses claims to check if token has expired or not, and this was probably breaking the code.
If you have any more questions, feel free to ask :)

Thanks
Mat

**Comment by PeterWone** [comment]
I've run into a bit of a problem. The OAuthService.loginOnStateChange method had to become a promise because it depends on OAuthService.getTokenDataFromUrl 

OAuthAuthorizeStep.run was already a promise so I rewrote it like this

```
  run(routingContext, next: Next) {
    if (this.oauthService) {
      return new Promise<any>((resolve, reject) => {
        this.oauthService.loginOnStateChange(routingContext.config).then(success => {
          if (success)
            resolve(next());
          else
            resolve(next.complete('Redirect'));
        });
      });
    } else {
      return next();
    }
  }

```
but this produces a circular reference error:
```
Unhandled rejection TypeError: Circular reference in value argument not supported
   at Anonymous function (http://localhost:9000/scripts/app-bundle.js:413:17)
   at OAuthService.prototype.loginOnStateChange (http://localhost:9000/scripts/app-bundle.js:412:13)
   at Anonymous function (http://localhost:9000/scripts/app-bundle.js:573:21)
From previous event:
   at OAuthAuthorizeStep.prototype.run (http://localhost:9000/scripts/app-bundle.js:572:17)
   at next (http://localhost:9000/scripts/vendor-bundle.js:25093:13)
   at iterate (http://localhost:9000/scripts/vendor-bundle.js:26092:7)
   at processDeactivatable (http://localhost:9000/scripts/vendor-bundle.js:26095:5)
   at run (http://localhost:9000/scripts/vendor-bundle.js:26027:7)
   at next (http://localhost:9000/scripts/vendor-bundle.js:25093:13)
   at Anonymous function (http://localhost:9000/scripts/vendor-bundle.js:25529:9)
From previous event:
   at run (http://localhost:9000/scripts/vendor-bundle.js:25527:7)
   at next (http://localhost:9000/scripts/
```
This looks like it's unhappy about a change of route happening before this one resolves. My ignorance of the internal magic of routes in Aurelia leaves me unable to deal with the problem.

**Comment by PeterWone** [comment]
Your instructions were more or less what I intended to do, and I've rewritten everything now. It works fine for Google and Microsoft.

Facebook makes it loop endlessly re-authenticating. Logging to the console shows it obtains a token, decodes the claims and saves the entire tokenData object before loading the page that triggered login. 

But for some reason Aurelia is restarted. Obviously it doesn't have the token after a restart, and so the cycle begins again. But I am at a loss as to why the restart occurs, and why only for Facebook - you'd think it would happen for all or none.

So anyway my code is now quite different from yours both in intent and structure. Do you want me to create a new repository as my own fork or do you want to update yours?

**Comment by matik12** [comment]
@PeterWone 

I see your problem according this info you have mentioned:

``` js
I have run into a bit of a problem. The OAuthService.loginOnStateChange method had to become a promise because it depends on OAuthService.getTokenDataFromUrl

OAuthAuthorizeStep.run was already a promise so I rewrote it like this

  run(routingContext, next: Next) {
    if (this.oauthService) {
      return new Promise<any>((resolve, reject) => {
        this.oauthService.loginOnStateChange(routingContext.config).then(success => {
          if (success)
            resolve(next());
          else
            resolve(next.complete('Redirect'));
        });
      });
    } else {
      return next();
    }
  }

but this produces a circular reference error:
```

I propose to leave authorize step as it was before and change logic related to getting claims, because this redirects could be more complex and can be connected with this step returning promises . What you could do to implement your flow, leave createToken and getTokenDataFromUrl methods synchronous as it was before without returning promises. In this case you don't have to change authorize step and loginOnStateChange. In setTokenOnRedirect method, change this line - this.oAuthTokenService.setToken(tokenData). So basically, set setToken could return promise and inside token service you can set claims according to parameter ie. setToken(token: any, setClaims: boolean) { ... }. This method could handle logic how to get claims, from api or token itself etc, and set property of token object. Only setting token could be promise, so small part of setTokenOnRedirect  method will depend on this promise resolve. I hope you can incorporate this changes into your code.

According to your last question, feel free to fork this repository and push your changes. The intent of this plugin was to keep it simple and provide only one-time identity provider setup. For that reasons, I am not considering to update the code base to support different scenarios in the near future. However, support for Facebook api could be added.

Mat

**Comment by PeterWone** [comment]
OK, thank you for your blessing. I agree that our my goal of versatility is not very compatible with your goal of simplicity.
